### PR TITLE
Fix contributor numbers when more than 100 of them

### LINKED ISSUE #1082: Optimize home page contributor section for 3 digits
We have a good problem this year of having over 100 contributors. The 2019 edition had "only" 92 contributors, so the UI only had to handle 2 digits. By expanding to 3 digits in 2020, some of the [contributor section](https://almanac.httparchive.org/en/2019/#contributors) styles may need to be optimized. As we continue to add translations of the 2019 edition, it may also end up exceeding 100 contributors as some point.

image

We have four breakpoints for various viewport widths, and the styling of this section changes in each one. For some in-between widths like 1300px shown above, the button style breaks. We should set `white-space: nowrap;` on the `.btn` styles to avoid this.

More generally, it seems like the `letter-spacing` of the `people-number` class could be improved as well as some of the relative positioning.

It may be a good idea to dynamically add something like a `three-digit` class to better differentiate between large and small numbers in the styles.

### PR DESCRIPTION
**Pull request by bazzadp**
Fixes #1082

### CODE REVIEW

**Comment by rviscomi** [comment]
Could you share a few screenshots of how it appears with different breakpoints?

**Comment by bazzadp** [comment]
Sure.

With this change:

image
image
image
image
image

image

Production:

image


image

image

image

image

image

**Comment by bazzadp** [comment]
I changed breakpoint of second one to make the big numbers smaller quicker. So this now looks like this:

image

**Comment by rviscomi** [comment]
Looks great! Yeah your change makes sense to give the text more room.

**Pull request merged**
