### PR TITLE
French Translation - All 2019 Authors

### PR DESCRIPTION
**Pull request by borisschapira**
Makes progress on #539

### CODE REVIEW

**Comment by bazzadp** [comment]
Planning on doing a release this evening. @nico3333fr do you want a chance to review this before I do that? Otherwise can merge as is and correct any mistakes later.

**Comment by nico3333fr** [comment]
@bazzadp sorry, it was too short for me ^^

**Comment by bazzadp** [comment]
No worries. Just didn't want to be so rude as to go ahead and merge if you were in the middle of reviewing so thought I'd comment!

**Comment by nico3333fr** [comment]
I'll check this one a bit later, I was off last week :)

**Pull request merged**
