### PR TITLE
Stop including chapters with no featured quote in home page

### PR DESCRIPTION
**Pull request by bazzadp**
This PR avoids this:

image

### CODE REVIEW

**Review by rviscomi — COMMENTED** [review]
This just removes the quote part but the features stats are still there? If so LGTM.

**Comment by bazzadp** [comment]
No. That’s what happens currently as per the screenshot.

What this does is return an empty object instead of a stat-only object. That makes it ineligible to be included and so we’ll just pick a random quote from any of the other chapters instead. We have 18 chapters with quotes so more than enough until the two missing ones finish out their meta data.

**Comment by rviscomi** [comment]
Oh ok, this is a rare edge case so I'm ok with hiding the chapter until more metadata is added, but given that there's still useful featured content to share I would have thought it be ok to still show the stats. No strong opinions either way, we still want to get that quote!

**Comment by bazzadp** [comment]
Also incentive for the chapter team to finish it out! 😀

**Review by rviscomi — APPROVED** [review]

**Pull request merged**
