### PR TITLE
Adds contributors for the security chapter of 2021

### PR DESCRIPTION
**Pull request by SaptakS**
Progress on #2150 

Adding the contributors for the security chapter. The progress for the same can be tracker [here](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2150)

cc @nrllh @tomvangoethem @GJFR @cqueern please check your informations and if anything needs to be changed/updated.

@edmondwwchan and @tunetheweb  were already added in the json file with reviewers positions, just added them to the chapter markdown file.

### CODE REVIEW

**Review by rviscomi — APPROVED** [review]

**Review by tunetheweb — APPROVED** [review]

**Comment by tomvangoethem** [comment]
Can you exclude me from the analysts? @GJFR did all the work!

**Comment by SaptakS** [comment]
@tomvangoethem done!

@tunetheweb @rviscomi resolved the merge conflicts

**Comment by cqueern** [comment]
> Can you exclude me from the analysts? @GJFR did all the work!

I did not contribute meaningfully this year. Can you please exclude me from the analysts as well?

**Comment by rviscomi** [comment]
@cqueern remove you from the reviewers list?

**Comment by cqueern** [comment]
@rviscomi please disregard [my comment above](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2522#issuecomment-971102579) because:
1. I accidentally referred to myself as an analyst instead of reviewer
2. I just spent time doing a full top to bottom review of the current draft and I'm comfortable being included as a reviewer

Apologies for the false alarm.

**Pull request merged**
