### PR TITLE
Performance 2022 Queries

### PR DESCRIPTION
**Pull request by konfirmed**
Progress on #2890 

# Queries:

### Web Getting Right (Not Custom)
- [x] % of sites that are using priority as an attribute on LCP element
- [x] % of sites where the LCP is element is preloaded

#### Gaming the Metrics (Custom)
- [x] Filtering for synthetic tests (does not catch hex codes, see https://www.simpleskincare.in/ for example)
- [x] LCP Animation & Overlay Hack
- [x] LCP Svg Overlay Hack
- [x] CLS Animation Hack
- [x] FID iFrame Hack

#### Antipatterns (Custom)

- [x] LCP Lazy Loaded

#### Antipatterns (Not Custom)

- [x] Are LCP Image Elements Responsive
- [x] LCP Element Resource Delay
- [x] TTFB by Category
- [x] Domain Sharding
- [x] FID Double Tap to Zoom Disabled
- [x] FID / INP Long Task Data (let's pick either FID or INP)

#### Web Vitals

- [x] By Device
- [x] By Country
- [x] By Network connection
- [x] By Rank
- [x] By Rank and device

### CODE REVIEW

**Comment by mel-ada** [comment]
I've added a [query list in the README](https://github.com/HTTPArchive/almanac.httparchive.org/blob/aa418613ef1200c65adb572ad2bf8843f44c3b74/sql/2022/performance/README.md#query-list), this is taken directly from the Metrics section in the linked planning doc!

**Comment by foxdavidj** [comment]
@25prathamesh @konfirmed Can you update the PR comment to include all of the metrics from Melissa she mentioned here? https://github.com/HTTPArchive/almanac.httparchive.org/blob/aa418613ef1200c65adb572ad2bf8843f44c3b74/sql/2022/performance/README.md#query-list

Looks like a lot of work has been done here. What queries still need to be written?

**Comment by siakaramalegos** [comment]
I just noticed the query list in the readme is not the same as here in the issue. So I appended those here because I'm really confused by what is done and not done. I just added all the web vitals queries from last year, updated the year, and added INP.

**Comment by mel-ada** [comment]
I've removed this section from the PR description and replaced it with the README since it is mostly overlap. Leaving it here for reference:
WIP
## Core Web Vitals Performance Past 

- [ ] Changelog


## Core Web Vitals Performance Present
### What is the web getting right? - Priority hints
- [ ] What is the effect on LCP?
- [ ] % of sites that are using priority as an attribute
- [ ] % of sites where the LCP is element is preloaded, 
-- [ ] and what is the order vs other requests that are preloaded

### What is the web getting wrong?

- [ ] Gaming the metrics
- [ ] Causes of slow performance

## Core Web Vitals Performance Present
- [ ] INP
- [ ] Bfcache®

**Comment by foxdavidj** [comment]
@mel-ada are so these are not additional metrics that need to be queried? But fully covered by what is listed in the description above?

@25prathamesh @konfirmed How possible is it to have the queries written and added to the spreadsheet by the end of the week (Aug 12th)?

Also i see that you're adding multiple metrics in one sheet. Each metric should be in a sheet named after the metric, like these here: https://docs.google.com/spreadsheets/d/1TPA_4xRTBB2fQZaBPZHVFvD0ikrR-4sNkfJfUEpjibs/edit#gid=555510064

Screen Shot 2022-08-09 at 09 03 21

**Comment by 25prathamesh** [comment]
HI @foxdavidj @mel-ada  @konfirmed @siakaramalegos 

Thanks for the feedback I will put each metric in its own sheet, with the sheet name being the same as the query file name.

@konfirmed  has already committed queries for the "What is the web getting right? - Priority hints" section, he will update data in the sheet 

4 queries are still pending from Antipatterns Section which are LCP Element Resource Delay, TTFB by Category, Domain Sharding, and FID Double Tap to Zoom Disabled 

I am already working on TTFB by Category query which I will commit to in the next 2 days,  having limited time during weekdays I will not able to complete the Rest of the 3 queries by 12 Aug. I will try to finish them on 14-15 Aug.

**Comment by mel-ada** [comment]
@foxdavidj Yes, all queries needed are captured in the PR description. [This comment ](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2974#issuecomment-1208827745) is the original PR description and can be disregarded, it's for reference incase the analysts still needed it.

**Comment by rviscomi** [comment]
@konfirmed @25prathamesh how can I help? We need to wrap this up ASAP so @mel-ada can write the draft, which is due in a couple of weeks.

**Comment by rviscomi** [comment]
I've added the remaining queries, tidied up the results sheet, and added charts where applicable. Some metrics have a single value for both desktop and mobile, and these work best as simple "big number" figures rather than charts, so I didn't make any.

Let's get the PR merged and iterate on the queries if needed. @mel-ada PTAL at the [results sheet](https://docs.google.com/spreadsheets/d/1TPA_4xRTBB2fQZaBPZHVFvD0ikrR-4sNkfJfUEpjibs/edit?usp=sharing) and let us know if you have any questions. For some of the more complex results I added some analyst notes in the form of comments and highlighted the cells in yellow.

Sorry for the delay, hopefully it was worth the wait as these results are super interesting. Looking forward to reviewing your draft!

**Pull request merged**
