### PR TITLE
Create and optimize large and small hero images

### PR DESCRIPTION
**Pull request by hyperpress**
Ref: #141 - Moved new, optimized images to design branch. Created an original jpg archive folder as these were dupes of XL images in master. Image sizes are **866px** wide for large and **326px** wide for small. Still need to correct paths in content, but images are ready.

### CODE REVIEW

**Comment by hyperpress** [comment]
I looked at all of them, and I don't see any difference between them.

**Comment by hyperpress** [comment]
I should know better than to listen to my gut on branches. I've never been right when I guess :-)

**Comment by hyperpress** [comment]
> Could you fix these and do a final sanity check to make sure they're all correct?
Good grief. Yeah, it's been a long couple of days and I screwed those up.  Will do a complete check before I bother you again with this.

**Comment by hyperpress** [comment]
Done. Sorry about the misplaced images. I did a complete sanity check.

**Comment by hyperpress** [comment]
Thanks for you patience @rviscomi  :+1:

**Comment by rviscomi** [comment]
No worries, thank you for contributing your time!

**Pull request merged**
