### PR TITLE
Copyediting SEO chapter

### PR DESCRIPTION
**Pull request by rachellcostello**
Progress on #218 

I've had another read through and have done a rewrite of this chapter. Mainly to improve structure, readability and flow rather than editing any of the data or findings.

### CODE REVIEW

**Comment by rviscomi** [comment]
Thanks for working on this! Putting all of my suggestions in a commit. I'll let you know when it's pushed into this PR.

Many of my edits are:

- sentence case for headings
- wrapping code in backticks
- US English spelling
- removing bold style from stats for consistency with other chapters

**Comment by rviscomi** [comment]
Just pushed my edits. Kind of hard to review given that the paragraphs don't have line breaks, but let me know if you see anything weird.

**Comment by rviscomi** [comment]
@obto FYI here's an example of an editing PR to give you an idea of the things we're looking for.

**Comment by rviscomi** [comment]
@rachellcostello any other edits or comments on my edits? We can merge if not.

**Comment by obto** [comment]
> @obto FYI here's an example of an editing PR to give you an idea of the things we're looking for.

Thanks! I'll give this a read tonight :)

**Comment by rachellcostello** [comment]
> @rachellcostello any other edits or comments on my edits? We can merge if not.

Nope, all looks good 👍  Thanks for looking through this.

**Pull request merged**
