### PR TITLE
Privacy 2021 Markdown

### PR DESCRIPTION
**Pull request by ydimova**
Progress on #2149

### CODE REVIEW

**Comment by tunetheweb** [comment]
Staged link: https://20211109t172922-dot-webalmanac.uk.r.appspot.com/en/2021/privacy

**Comment by tunetheweb** [comment]
Featured quote on home page:

image

Can re change the first two to one figure? Less confusing. Normally give mobile unless good reason to go with desktop.

**Comment by tunetheweb** [comment]
As per the slack, I've rerun the images (Sheets only):
- Sheets Embeds (new): https://20211110t201045-dot-webalmanac.uk.r.appspot.com/en/2021/privacy
- Images (original): https://20211110t201045-dot-webalmanac.uk.r.appspot.com/en/2021/privacy?print

If happy with those edits will retake the images and add to this branch.

Let me know if you're finished here and if this chapter is now ready for editing?

**Comment by VictorLeP** [comment]
> As per the slack, I've rerun the images (Sheets only):
> 
> * Sheets Embeds (new): https://20211110t201045-dot-webalmanac.uk.r.appspot.com/en/2021/privacy
> * Images (original): https://20211110t201045-dot-webalmanac.uk.r.appspot.com/en/2021/privacy?print
> 
> If happy with those edits will retake the images and add to this branch.
> 
> Let me know if you're finished here and if this chapter is now ready for editing?

I resized a few charts, but otherwise they're OK to retake.

For me, the chapter is then ready for editing!

**Comment by VictorLeP** [comment]
> Featured quote on home page:
> 
> image
> 
> Can re change the first two to one figure? Less confusing. Normally give mobile unless good reason to go with desktop.

Done in 05b4920.

**Comment by tunetheweb** [comment]
I've added the unedited flag so am going to merge this and open a new PR for the edits.

**Pull request merged**
