### PR TITLE
Caching queries

### PR DESCRIPTION
**Pull request by obto**
Queries for chapter 16, caching

Progress on #97

### CODE REVIEW

**Comment by rviscomi** [comment]
Did you happen to save the results to a spreadsheet for review? ☺️

**Comment by obto** [comment]
Is the doc for chapter 16's data created yet? If you shoot me the link I'll add the data right now.

**Comment by rviscomi** [comment]
Created [this sheet](https://docs.google.com/spreadsheets/d/1mnq03DqrRBwxfDV05uEFETK0_hPbYOynWxZkV3tFgNk/edit?usp=sharing) and gave you and @paulcalvano edit access

**Comment by obto** [comment]
Data has been added. 16.06 - 16.10 are ready for review

**Comment by rviscomi** [comment]
@paulcalvano are you able to review these queries/[results](https://docs.google.com/spreadsheets/d/1mnq03DqrRBwxfDV05uEFETK0_hPbYOynWxZkV3tFgNk/edit?usp=sharing)?

**Comment by rviscomi** [comment]
🛎 One more ping for @paulcalvano 👋🤠💼

**Comment by obto** [comment]
@rviscomi @paulcalvano 

All done and ready for review. The two remaining metrics I have questions about:

1. 16_03: What are we looking for when you say `Cache strategy`?
2. 16_11: 1st Party vs 3rd Party Caching. What parts would you like to compare?

**Comment by paulcalvano** [comment]
Awesome thanks @obto .  WIll review these today.

**Comment by paulcalvano** [comment]
@obto - These look awesome. Really nice work! I just finished reviewing them.  The queries 16.01, 16.02, 16.04, 16.06, 16.07, 16.09, 16.10 and 16.15 look good.

In 16.05 you are using `TRIM(resp_etag) = "" AS uses_etag` to identify whether an etag is present, and then COUNTIF(uses_etag) to count the number of true occurrences. It looks like the values are inverted, and you are actually counting the number of requests that do not use etags.

image

There's a similar issue on 16.08, where the numbers for uses_expires appear to be reversed - 

image

Also on 16.12 and 16.13 for  uses_cache_control

image


Let's skip 16.03.  I don't remember what that one was about :)

For 16.11, I was thinking of analyzing cacheability  by content type - so similar to 16.02 but splitting out first vs third party.   I did something like this in a [discuss artcle ](https://discuss.httparchive.org/t/analyzing-resource-age-by-content-type/1659) 

Thanks again for working on this!

**Comment by obto** [comment]
@paulcalvano great catch on trim(X) = "" there! That problem should now be fixed :smile: 

Regarding 16.11, sounds good. I'll push that metric out tomorrow then

**Comment by paulcalvano** [comment]
This looks good.  Thanks!

**Comment by obto** [comment]
Sorry about the delay, got swamped with work today. I'll try and have the last query out tomorrow :)

**Comment by rviscomi** [comment]
@obto feel free to merge when the final query is in 👍

**Comment by obto** [comment]
@paulcalvano @rviscomi I added 1st vs 3rd party versions for each applicable query. The queries are the same, but if either of you could give it a quick once over that'd be great :)

Also, this is really interesting data. Areas that looked like we had poor performance in (like cache ttl)... are often due to how bad the 1st party requests are. Great idea to look into this :+1:

**Pull request merged**
