### PR TITLE
Fix extra paragraph tags (simple fix)

### PR DESCRIPTION
**Pull request by bazzadp**
Simple fix for https://github.com/HTTPArchive/almanac.httparchive.org/issues/412 (proper fix to follow possibly).

### CODE REVIEW

**Comment by mikegeyser** [comment]
I've pushed virtually the same fix to the `extra-p-tags` branch, except that it is in a separate script file. Could we go with that, or is it unnecessary? (Just checking, was about to open a PR.)

**Comment by bazzadp** [comment]
> I've pushed virtually the same fix to the `extra-p-tags` branch, except that it is in a separate script file. Could we go with that, or is it unnecessary? (Just checking, was about to open a PR.)

Seems a bit excessive IMHO. Especially for a short-term hack (though they often have a habit of hanging around!).

**Comment by bazzadp** [comment]
Though do like the name of it (`remove_unnecessary_markup.js`) as suggests could be used for more than just this hack...

**Comment by mikegeyser** [comment]
That was my thinking. Keep all of the awful hacks in a single place, so we can go about fixing them.

**Comment by bazzadp** [comment]
OK lets close this and go with your fix. Also has the handy extra bonus of blaming you for this complete hack 😀

**Comment by rviscomi** [comment]
Open to either approach. I defer to the PR author!

**Comment by mikegeyser** [comment]
@bazzadp Please take a look, and go ahead if you're happy.

**Comment by bazzadp** [comment]
> @bazzadp Please take a look, and go ahead if you're happy.

Already looked and happy with your approach. go ahead and raise a PR. Closing this and deleting my branch.

**Pull request closed without merging**
