### PR TITLE
SEO 2022 Queries

### PR DESCRIPTION
**Pull request by csliva**
Progress on #2888 

Contents of PR are duplicated from the [Google doc outline](https://docs.google.com/document/d/15udJOrPhwV0yWP8cviwRyapSssCUrLxkX29KbJNJH4Q/edit#)

## Robots.txt

- [x] mobile/desktop response codes
- [x] How many sites completely block crawling. % of websites which completely block Googlebot / Bingbot. 
- [x] File size any over the 500KiB limit. 

## MetaRobots 

- [x] Meta robots vs x-robots usage. Desktop/mobile differences. Change since last year. +image
- [x] What values are returned? Noindex, nofollow, nosnippet, max-image-preview, none, all, etc. Are values changed when rendered, especially index/noindex? 
- [x] New indexifembedded meta tag usage – is it being used, any trend in where it’s being used or how? 
- [x] Invalid elements in <head> - Google’s released new documentation on this. Assess % of sites that are using invalid elements in <head> 

## Canonicals 

- [x] HTML Head vs HTTP header implementation, any in the body tags unrendered?
- [x] Has canonical, canonicals to self or other page +image
- [x] Usage of relative vs absolute vs schemaless URL?
- [x] Any changes that happen to canonicals when rendering? Change in page or added or removed? Any moved to the body tag when rendered? 
- [x] How many pages has more than one  canonical tag specified? 

## Page Experience

- [x] Core web vitals scores -  pass/fail broken down by FCP/CLS/TBT/LCP/INP/TTFB – any trends? % that passed / failed mobile friendly test. 
- [x] Mobile vs desktop (as desktop is now a factor)
- [ ] CDN - number of websites using CDN / particular types of CDN
- [x] HTTPS desktop vs. mobile comparison YoY
- [x] Viewport meta tag usage, desktop/mobile, yearly changes
- [x] CSS media queries, desktop/mobile, yearly changes
- [x] Vary user-agent usage, desktop/mobile +image
- [x] Legible font sizes - lighthouse, most common text sizes
- [x] Unused CSS, JS + Image 

## Images

- [x]  elements
- [x] Alt attributes

## CMS Platforms 

- [ ] most popular CMS types (which can lead into individual chapter)

## On Page 

- [x] Page titles - Number of missing page titles. Page titles too long / too short. 
- [x] Meta descriptions: number of sites which have inputted meta descriptions. Too long/too short split. 
- [x] Keywords - % of websites using meta keywords.
- [x] Word count - avg. word count on pages vs. last year & 2020.  
- [x] Average # of heading tags, breakdown per type (h2/h3/etc)

## Server 

- [ ] most popular servers used. Types of server (dedicated/shared/cloud).  
- [ ] Server-side rendering (SSR) vs. client-side rendering (CSR) - % of websites using SSR vs. CSR
- [ ] % of service-side rendering that’s dynamic

## Links

- [x] do follow/no follow split (note for author - tie in something around digital PR and increase in nofollow links as digital PR has trended in the last year if the data matches this theory), 
- [x] rel=ugc & rel=sponsored - % of links using these attributes 
- [x] anchor text usage
- [x] number of external links (copying from last year)

## Structured data

- [ ] Is the page using structured data? Is there a correlation in most used type of structured data by industry?
- [ ] What % of sites implement structured data with more than one method e.g. JSON-LD & microdata
- [ ] Can we split this by CMS? To see which CMS is adding what markup by default (potentially) e.g. on Wix if you have a physical address on the homepage, you’ll automatically have local business structured data added. % split between manual & automatic implementation. 

## Mobile vs. Desktop 

- [x] Word count
- [x] Links
- [x] Structured data
- [x] Hreflang +image
- [x] Meta robots
- [x] Alt attributes on images +image
- [x] AMP 
- [ ] AMP. Usage. AMP-only. Vs 2021 & 2020. Desktop/Mobile.

## Rendered vs non-rendered differences?

- [ ] Word count
- [ ] Things missing and then not, or things changed? Titles, meta descriptions, robots meta tags, structured data, links, etc.

## Internationalisation 

- [x] Content-language usage. Headers vs meta tags for content language also. 
- [x] Most common values of the hreflang attribute

### CODE REVIEW

**Comment by foxdavidj** [comment]
@derekperkins @csliva @jroakes How are the queries coming along?

**Comment by csliva** [comment]
Hey @foxdavidj I'm going to get cracking on this and hopefully finish the work by deadline end of month. I'll also ping @jroakes and @derekperkins to see what their bandwidth looks like.

**Comment by SophieBrannon** [comment]
Hey @csliva how are we getting on with this?

**Comment by foxdavidj** [comment]
@csliva Are the checkboxes in the PR description up to date?

**Review by rviscomi — APPROVED** [review]
All chapters should be standardizing on the June dataset (`2022_06_01`) however I see all of these queries are over the July dataset.

Given that the analysis is two weeks overdue and the high effort required to replace all of the dates, rerun the queries, and overwrite the results in the sheet, I don't think we have any other choice but to merge as-is.

**Pull request merged**
