### PR TITLE
Fix one last TODO comment in 2020 Performance chapter

### PR DESCRIPTION
**Pull request by bazzadp**
Looks like I missed one in #1622 

@thefoxis you OK with this change?

@borisschapira / @Zuckjet FYI as you're busy translating this chapter.

### CODE REVIEW

**Comment by bazzadp** [comment]
GitHub not highlight the changes very nicely!

It just changes this:

> Again, it isn't easy to speculate why that might be {# I think it IS easy to speculate why - precisely for the reasons you give! #}. 

to this:

> Again, we can speculate why that might be, but would need further analysis to really be sure.

**Comment by Zuckjet** [comment]
in the section of "FCP by connection type"， this words:

" so ensuring text is visible while web fonts are downloaded is also a worthwhile strategy"

I think it need to change to like this "Ensure text remains visible during webfont load".

should be downloading process not done. sorry for bad format because of away from my computer

**Comment by bazzadp** [comment]
> in the section of "FCP by connection type"， this words:
> 
> " so ensuring text is visible while web fonts are downloaded is also a worthwhile strategy"
> 
> I think it need to change to like this "Ensure text remains visible during webfont load".
> 
> should be downloading process not done. sorry for bad format because of away from my computer

The current text reads fine to me:

> FCP is also significantly affected by font load time, so ensuring text is visible while web fonts are downloaded is also a worthwhile strategy (especially where on slower connections these resources will be costly to fetch).

Not sure I get your concern?

**Comment by Zuckjet** [comment]
my understand is that we should emphasize the process of downloading. that is to say the difference between "font have downloaded" and "font is downloading".

Maybe my understand is mistake, if so just ignore.

**Comment by bazzadp** [comment]
Getting into the depths of English grammar that are beyond me! 😁 However, to me, this:

> FCP is also significantly affected by font load time, so ensuring text is visible while web fonts are **downloaded** is also a worthwhile strategy (especially where on slower connections these resources will be costly to fetch).

reads the same as this:

> FCP is also significantly affected by font load time, so ensuring text is visible while web fonts are **downloading** is also a worthwhile strategy (especially where on slower connections these resources will be costly to fetch).

I don’t think the first implies past tense (i.e. that they have been downloaded already) and it’s more along the lines of “..while web fonts are downloaded in parallel in the background”.

**Review by thefoxis — APPROVED** [review]

**Comment by thefoxis** [comment]
@bazzadp approved 👍 thanks for that!

the two sentences above read identical to me too, I think especially that `while` is used before the subject and the verb 😸

**Pull request merged**
