### PR TITLE
SEO 2021 queries

### PR DESCRIPTION
**Pull request by obto**
Queries for #2146

Note: refer to [last year's queries](https://docs.google.com/spreadsheets/d/1ram47FshAjzvbQVJbAQPgxZN7PPOPCKIK67VJZCo92c/edit) for additional comments

### CODE REVIEW

**Comment by obto** [comment]
@jessthebp @jroakes @rvth Here is the PR with all of the updated queries.

@tunetheweb @rviscomi When the other SEO analysts add new queries how should we handle the PR?

1. Have them commit their changes to my branch here?
2. Create a separate PR with just their new queries, so we can merge both PRs without conflicts?

**Comment by tunetheweb** [comment]
> @tunetheweb @rviscomi When the other SEO analysts add new queries how should we handle the PR?
> 
> 1. Have them commit their changes to my branch here?
> 2. Create a separate PR with just their new queries, so we can merge both PRs without conflicts?

It would have been better if you'd created this PR in the almanac repo, that way others would have edit access to it and could add to this branch without you having to mess about granting permissions in your own repo. Could you create a new branch here with these changes?

**Comment by jroakes** [comment]
Will wait on response to @tunetheweb before proceeding in case this PR moves.

**Comment by obto** [comment]
> > @tunetheweb @rviscomi When the other SEO analysts add new queries how should we handle the PR?
> > 
> > 1. Have them commit their changes to my branch here?
> > 2. Create a separate PR with just their new queries, so we can merge both PRs without conflicts?
> 
> It would have been better if you'd created this PR in the almanac repo, that way others would have edit access to it and could add to this branch without you having to mess about granting permissions in your own repo. Could you create a new branch here with these changes?

Good idea. Will do

**Comment by obto** [comment]
Closed in favor of #2351

**Pull request closed without merging**
