### PR TITLE
Performance Chapter 2022 Markdown

### PR DESCRIPTION
**Pull request by mel-ada**

### CODE REVIEW

**Comment by mel-ada** [comment]
Meant to open as a draft. Will close this one.

**Comment by rviscomi** [comment]
@mel-ada best to wait until the draft is reviewed and edited before converting to markdown, because it's easiest to iterate in Docs. If your concern is timing, I can take care of the md conversion while you're away.

**Comment by mel-ada** [comment]
> 
Yeah, won't start adding content until it's approved. Wanted to have it ready for whenever that is in hopes of not having to take you up on your offer (thank you!) or at least doing as much as possible before I'm unavailable. Let's revisit as the review/edit process unfolds.

**Comment by mel-ada** [comment]
@rviscomi FYI ^^

**Comment by rviscomi** [comment]
Good plan thanks for clarifying

**Pull request closed without merging**
