### PR TITLE
Next/Prev chapter broken styles

### LINKED ISSUE #315: Next/Prev chapter broken styles
When there are no previous chapters, the next/prev widget at the bottom of the chapter page appears to lose its vertical centering and spacing:

image

It should look consistent with this:

image

@tyohan can you take a look at this or unassign yourself if not?

### PR DESCRIPTION
**Pull request by catalinred**

### CODE REVIEW

**Comment by rviscomi** [comment]
@catalinred this was a small change so no big deal but FYI it's good to get an LGTM from someone before merging :)

**Comment by catalinred** [comment]
> @catalinred this was a small change so no big deal but FYI it's good to get an LGTM from someone before merging :)

Uh oh, I didn't merge anything. 

Actually I messed it up with this pull request because of a rebase (see the above no of commits) and this is why I closed it as soon as I noticed it.

I opened another pull request, a clean one this time: #341 

Sorry for this mess for this small change :(

**Comment by rviscomi** [comment]
Ahhh ok my mistake. I glanced quickly and assumed it was merged 😊

**Comment by catalinred** [comment]
Nah, my bad. You're being too kind :)

I created such a chaos for a simple commit. Also, I will keep in mind the squash+merge thing next time. Thanks!

**Pull request closed without merging**
