### PR TITLE
Copyedit Caching 2020

### PR DESCRIPTION
**Pull request by bazzadp**
Makes progress on #1432 and #917

Quite a large edit this one to be honest. The below are the main changes:
- Quite a lot of parenthesis, dashes and bullet lists. Not judging as I do this far too much too, but tried to reign it in a bit to make it more readable.
- Moved to mobile stats as primary rather than desktop. This is more in-line with the rest of the as Web Almanac we have more data and also Lighthouse stats. It is of particular importance here as you switch to some mobile-only stats (ServiceWorkers and other Lighthouse data) so find it less confusing to just stay with mobile all the way through.
- Removed statements that browser caches are "instant" since they aren't and can also [be slower than networks in some cases](https://simonhearne.com/2020/network-faster-than-cache/). Also added a link to that post.
- Moved the cat picture to JPG as a lot smaller (left the PNG one for now in case anyone is referencing it).
- Minor tweaks on some of the images and also recompressed them all (mostly very small gains to be honest so looks like you had them pretty well compressed already!).
- Removed a lot of quotes I felt were unnecessary and distracting.
- Reordered some of the figures (we prefer stats first, then interpretation afterwards).
- Aligned figure labels to chart titles.
- Moved `<pre><code>` to markdown (```), unless HTML was being used, as slightly more readable
- Added a note about ETag bugs [including a reference of my own](https://www.tunetheweb.com/performance/http-performance-headers/etag/#downsides) — hope this is not to presumptuous but think it's relevant here.
- Code formatted and numeric formatted.
- Removed "Unedited" tag.

Do realise that is a lot of change so let me know if you've any questions of concerns about any of the above, or feel free to comment on any individual changes using the Files tab and the [review pull requests functionality of GitHub](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request).

Was a very good read and just trying to make it slightly more readable and more in-line with the rest of the Web Almanac.

I've staged this version here: https://20210123t173808-dot-webalmanac.uk.r.appspot.com/en/2020/caching
if you want to compare it to production: https://almanac.httparchive.org/en/2020/caching

### CODE REVIEW

**Comment by bazzadp** [comment]
You OK if I merge this @roryhewitt @raghuramakrishnan71 or do you want more time to review?

**Comment by bazzadp** [comment]
Nearly missed this @raghuramakrishnan71  about was just about to merge this as you edited my comment!

> @bazzadp will require a few more days - mid of next week. thanks.

No bother, will merge if I haven't heard back from you by this time next week.

**Comment by bazzadp** [comment]
Going to merge this. We can open a new pull request for any further edits.

**Comment by roryhewitt** [comment]
@barrypollard I'm fine with you merging (he says, as it's already been merged :))

**Comment by roryhewitt** [comment]
@barrypollard I hadn't seen you ETag-related document before - that's a great resource, and should certainly be linked to. FWIW, I wasn't aware that Apache gave you so few options to generate ETags - I always assumed that it was possible to manually create an ETag for a file using whatever system you prefer - hence my discussions about the possibility of just putting a version string in there. ETags are great, and (IMHO) poorly supported by assorted web servers (as well as by my own company, which doesn't support weak ETags at all, but that's another discussion).

**Comment by bazzadp** [comment]
> @barrypollard I'm fine with you merging (he says, as it's already been merged :))

Sorry but thought I'd given enough time and was keen to call it a day on 2020 edition. It's now complete with no more "Unedited" tags in any chapter. Woo hoo!

> FWIW, I wasn't aware that Apache gave you so few options to generate ETags - I always assumed that it was possible to manually create an ETag for a file using whatever system you prefer - hence my discussions about the possibility of just putting a version string in there.

Yeah I agree ETags can be good, but are being held back by poor web server support. Apache's lack of options aren't the real problem - the fact it basically breaks 304s for gzipped files are the real problem! Still an issue if you look at [their home page](https://httpd.apache.org/) and refresh (with "Disable cache" unticked) and it returns a 200 on refresh:

Apache 200 instead fo 304

Compared [with my own site](https://www.tunetheweb.com/) which uses Apache without ETags:

Apache returning 304 correctly

And that couple with the lack of options meaning they are basically the same as `Last-Modified`, means (IMHO) they really can't be recommended.

**Pull request merged**
