### PR TITLE
Media 2021 queries (#2144)

### PR DESCRIPTION
**Pull request by eeeps**
Progress towards #2144 

(Initially empty) PR to track progress on Media 2021 queries.

Queries we need (based on the outline)

♻️ = try to use same query from 2019/2020 in order to facillitate comparison over time

### Impact

- [x] distribution of image bytes / page ♻️
  - link to [page weight](https://docs.google.com/spreadsheets/d/1XApPAC8m2jLJR3Ok1yAoc9PzAFtq-Z41LoakXHUVeag/edit#gid=895329225), possibly do focused (image-only) visualizations of this data, comparing to [previous years](https://docs.google.com/spreadsheets/d/1XApPAC8m2jLJR3Ok1yAoc9PzAFtq-Z41LoakXHUVeag/edit#gid=2072048762)
- [x] distribution of image pixels / page pixels (viewport pixels?) ♻️
- [x] Images and LCP (link to performance's awesome analysis)
- [x] prevalence of <del>tracking</del><ins>1x1</ins> pixels

### Content

- [x] Dimensions
- [x] Aspect ratios

### Encoding

- [x] format use
- [x] bits / pixel by format

### Embedding

- [x] lazy loading ♻️
  - [x] timeseries (https://httparchive.org/reports/state-of-images#imgLazy) @rviscomi 
  - link to performance's (awesome!) analysis re: overuse
- srcset
  - [x] adoption ♻️
  - [x] w vs x descriptors ♻️
  - [x] number of candidates  ♻️
  - [ ] densities (distribution of currentSrcDensity values, distribution of srcsetCandidateDensities values) @rviscomi 
- sizes
  - [x] implicit vs explicit (of images with srcsetHasWDescriptors what percent are sizesWasImplicit) @eeeps 
  - [x] valid vs invalid (of images with srcsetHasWDescriptors what percent have sizesParseError) @eeeps 
  - [x] most-common explicit values ♻️ @eeeps 
  - [ ] (in)accuracy -- compare sizes size to layout size ([10, 25, 50, 75, 90] distribution: sizesAbsoluteError and sizesRelativeError, % of images with sizesRelativeError < 0.05) @rviscomi 
- picture
  - [x] adoption
  - [ ] type-switching vs art-direction ♻️ (for images with isInPicture what percent has pictureMediaSwitching vs pictureTypeSwitching) @rviscomi 
    - most interesting exotics (not min-width or max-width)
- width and height attributes
  - [x] how many images have both?
  - [x] how often are they used to reserve space for flexible images?
- accessibility
  - [x] alt ♻️
  - [x] figcaption ♻️
- [x] async attribute adoption

### Layout

- [ ] intrinsic vs extrinsic sizing (percent of images broken down by intrinsicOrExtrinsicSizing for height and width) @rviscomi 

### Delivery

- [x] Cross-origin vs same-origin
   - link to Resource Hints re: preconnect for cross-origin resources
- [x] URL-based resizing
 

## Video

- [x] Doug did it!

### CODE REVIEW

**Comment by eeeps** [comment]
@dougsillars could you enumerate the queries we'll need to complete the video section?

**Comment by rviscomi** [comment]
Converting the PR to draft for now. @eeeps please mark "Ready for review" when ready.

**Comment by rviscomi** [comment]
@eeeps @dougsillars how's the analysis going? Is there anything I can do to help?

**Comment by dougsillars** [comment]
When are they due?  I havent gotten to the queries yet.

**Comment by rviscomi** [comment]
Milestones and due dates are documented at the top of the [chapter issue](https://github.com/HTTPArchive/almanac.httparchive.org/issues/2144#issue-868435743). We allocated 2 months for analysis, so it's due September 30 to stay on schedule. Since you're both authors and analysts, it's ok if you need to spend more time on analysis, as long as you know that you'll have less time for writing.

**Comment by rviscomi** [comment]
Let us know if there's anything we can do to help keep the analysis on track.

**Comment by rviscomi** [comment]
Hi @dougsillars @eeeps is there anything I can do to help unblock this PR?

**Comment by dougsillars** [comment]
I'll work on this this week.

**Comment by rviscomi** [comment]
Thanks @dougsillars. Let me know if I can help at all! Just 4 more weeks left for authoring so I want to make sure you have enough time.

**Comment by eeeps** [comment]
Not ready, still working. @akshay-ranganath and I have split up the remaining work; hoping to have something to review early next week.

**Comment by akshay-ranganath** [comment]
Hi @rviscomi . I have adopted a bunch of queries from last year and issued a pull request to @eeeps just now. Hopefully, we'll have this done soon.

**Comment by rviscomi** [comment]
Thanks @akshay-ranganath!

**Comment by rviscomi** [comment]
@akshay-ranganath @eeeps could you update the [checklist above](https://github.com/HTTPArchive/almanac.httparchive.org/pull/2308#issue-970769716) to reflect what (if any) remaining queries there are? This needs to be reviewed and merged ASAP.

**Comment by rviscomi** [comment]
Lazy-loading timeseries can be repurposed from https://almanac.httparchive.org/en/2021/resource-hints#fig-15
Chart: https://docs.google.com/spreadsheets/d/1Mw6TjkIClRtlZPHbij5corOZbaSUp-vgTVq3Ig18IwQ/edit#gid=157636784
Figure markdown: https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/content/en/2021/resource-hints.md?plain=1#L581-L589

**Comment by rviscomi** [comment]
See https://github.com/HTTPArchive/almanac.httparchive.org/pull/2583

**Pull request closed without merging**
