### PR TITLE
Add Results and Queries buttons to each chapter

### LINKED ISSUE #221: Give readers the ability to discover queries, results, and comments for each chapter
Each chapter has a subdir in [sql/2019](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/sql/2019) with all of its queries and a corresponding spreadsheet with the results.

We should make these resources available to readers as they're on a chapter page. These aren't included in the design so we'll need to create it from scratch using the existing visual language of the site.

In the chapter designs (#130) we have a section for info about each author at the bottom of the page. We can use this space to also call attention to the chapter's SQL subdir and results sheet.

Additionally, I'd like to provide readers with an easy way to react to, report issues with, and comment on chapters. I'm not really sure what the best approach is, so I'm open to ideas. One idea is to create a GitHub issue for each chapter devoted to reader feedback. I don't really like keeping issues open perpetually, though, and GitHub isn't meant to be a discussion forum. We do have the HTTP Archive discussion forum at discuss.httparchive.org where we can do something similar. Thoughts?

---

- [x] Add a new field to each chapter's markdown metadata `discuss` whose value is the four digit thread ID corresponding to the chapter's discussion post. For example `1756` is the ID for the JavaScript thread: https://discuss.httparchive.org/t/chapter-1-javascript/1756
- [x] Add a UI component to the end of the chapter template to encourage readers to discuss their thoughts. It could be something simple like a link button with a chat icon and the label "Comments".
- [x] Generate the link href value based on the chapter's metadata.

Commenting is the biggest priority for launch. We can follow up with UI to discover the queries and results later.

@HTTPArchive/developers

### PR DESCRIPTION
**Pull request by bazzadp**
Fixes #221 . Should have done this ages ago as quick nice to have the links in each chapter!

Just knocked together some quick icons myself but let me know if you have better ones to use

**Desktop:**

desktop

**Mobile**:

mobile

### CODE REVIEW

**Comment by bazzadp** [comment]
BTW could make this cleaner and remove one bit of chapter meta data I added in this PR (`queries` metadata) if we renamed the [sql directory](https://github.com/HTTPArchive/almanac.httparchive.org/tree/master/sql/2019) to be named by chapter slug (similarly to what I did with the image folders in #683). WDYT @rviscomi ?

**Comment by rviscomi** [comment]
IIRC there are some external links floating around that point directly to the SQL directories. Also, I still like how they are prefixed by chapter number so the directories can be browsed in order. So my preference is to keep the naming as is.

My only comment for this PR is that my original intent was to link each figure with its corresponding tab in the spreadsheet so readers can go directly to the underlying data that powers the chart. Since the spreadsheets are indexed by metric ID and not figure number, there is no clear mapping for readers to reference data for a specific chart and it might be a bit disorienting. Overall, it's an improvement, so I'm happy to land this change. I don't think we need to itemize each chart with its corresponding data sheet for 2019, but something to consider moving forward.

**Comment by bazzadp** [comment]
Fair points - though not sure I 100% agree the average reader would rather have folders in chapter order rather than alphabetical order but don't feel strongly about ti one way or the other and, unlike images, can't redirect if it has been linked so happy to leave as is.

Anyway, as you say, this is an improvement as points them in the right direction. And think the summary at the end (near the discussion link) is quite a good way of doing it, so even if we add figure-specific links, way may want this anyway.

Merging this in now anyway!

**Comment by borisschapira** [comment]
French is right here too, thanks @bazzadp

**Pull request merged**
