### PR TITLE
Add dropdown menu to show extra figure information

### LINKED ISSUE #1138: Streamline figures in markdown
I'd like to propose a change in the way figures are described by authors in the markdown and rendered internally.

image

In [css.md](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/src/content/en/2019/css.md), the corresponding markdown (using embedded HTML) for the figure above is:

```html
<figure>
  <a href="/static/images/2019/css/fig12.png">
    <img src="/static/images/2019/css/fig12.png" alt="Figure 12. Adoption of flexbox." aria-labelledby="fig12-caption" aria-describedby="fig12-description" width="600" height="371" data-width="600" data-height="371" data-seamless data-frameborder="0" data-scrolling="no" data-iframe="https://docs.google.com/spreadsheets/d/e/2PACX-1vQO5CabwLwQ5Lj1_9bbEFnFM1qEqCorymaBHrcaNiMSJ7sYDKHUI5iish5VAS-SxN447UTW-1-5-OjE/pubchart?oid=2021161093&amp;format=interactive">
  </a>
  <div id="fig12-description" class="visually-hidden">Bar chart showing 49% of desktop pages and 52% of mobile pages using flexbox.</div>
  <figcaption id="fig12-caption">Figure 12. Adoption of flexbox.</figcaption>
</figure>
```

One thing I'd like to improve is the figure numbering. The figure ID is automatically generated, but we're still manually writing `Figure 12` in the `<figcaption>` and managing the IDs needed for the accessible description. Can all of this be automated? I'd also like to make all figure numbers unique and prefixed by chapter number. So rather than `Figure 12` this would be `Figure 2.12`.

The `fig12.png` image shouldn't be named according to its figure number. These names aren't descriptive and must be kept in sync with the figure ordering in the chapter. Instead, we should name figure images descriptively, like `flexbox-adoption.png`. We should use this name as the `<figure id>` and permalink so that reordering figures wouldn't make old links obsolete.

I would also love to see all figures accompanied by links to their metadata like the corresponding SQL file and results sheet. This would enable anyone to see how the metrics were calculated and run it themselves. This requires some design choices like how to provide these links unobtrusively and accessibly. My idea is a menu in the corner of the figure, similar to the [HTTP Archive metrics](https://httparchive.org/reports/state-of-the-web#numUrls):

image

Rather than generating figure numbers in the build process, I wonder if this could be done entirely in the templates. For example, could authors include a Jinja macro like this:

```python
{%
  figure(
    # Figure ID corresponding to the `png` image and `sql` file name.
    'flexbox-adoption',
    # Figure caption.
    'Adoption of flexbox.',
    # Detailed figure description.
    'Bar chart showing 49% of desktop pages and 52% of mobile pages using flexbox.',
    # Embedded Sheets URL. (maybe we can add the base of this URL to the chapter yaml and only include the relevant IDs?)
    'https://docs.google.com/spreadsheets/d/e/2PACX-1vQO5CabwLwQ5Lj1_9bbEFnFM1qEqCorymaBHrcaNiMSJ7sYDKHUI5iish5VAS-SxN447UTW-1-5-OjE/pubchart?oid=2021161093&amp;format=interactive',
    # Tab ID in Sheets for this metric's results. For example `/edit#gid=1861654265`.
    '1861654265',
    # Optional width and height if non-standard (600x371).
    600, 371
  )
%}
```

----

There are other kinds of figures, like big numbers:

image

```html
<figure>
  <div class="big-number">2%</div>
  <figcaption>Figure 13. Percent of websites using grid.</figcaption>
</figure>
```

Even though the markup for this figure is much simpler, I would love to see another macro to standardize the boilerplate across all chapters so that the developers have more centralized control over how these are generated. We could have a macro like this:

```python
{%
  figure_big_number(
    # Figure ID corresponding to the `sql` file name.
    'grid-adoption',
    # The big number.
    '2%',
    # Figure caption.
    'Percent of websites using grid.',
    # Tab ID in Sheets for this metric's results.
    '1459448594'
  )
%}
```

We should build some customizability into these macros. For example, we needed to adjust the appearance of the [z-index](https://almanac.httparchive.org/en/2019/css#fig-22) "really big number" figure. Perhaps there could be an optional parameter for a classname to be added to the figure. This could be used to adjust the font size as in the z-index example, create "alternate" themes for the big numbers so that they're not all the same color, etc.

---- 

We also need to support other types of figures: tables, images, and videos. The [2019 Mobile Web](https://almanac.httparchive.org/en/2019/mobile-web) chapter uses all three in the first three figures.

```html
<figure>
<table>
  <tr>
    <th>Connection type</th>
    <td><a href="https://www.gsma.com/r/mobileeconomy/">2G or 3G</a></td>
  </tr>
  <tr>
    <th>Latency</th>
    <td>300 - 400ms</td>
  </tr>
  <tr>
    <th>Bandwidth</th>
    <td>0.4 - 1.6Mbps</td>
  </tr>
  <tr>
    <th>Phone</th>
    <td><a href="https://www.gsmarena.com/samsung_galaxy_s6-6849.php">Galaxy S6</a> — <a href="https://www.notebookcheck.net/A11-Bionic-vs-7420-Octa_9250_6662.247596.0.html">4x slower</a> than iPhone 8 (Octane V2 score)</td>
  </tr>
</table>
<figcaption>Figure 1. Technical profile of a typical mobile user.</figcaption>
</figure>
```

I think it's ok to include the `<figure>` HTML although it may be nice to use markdown tables when possible. It may be harder to get the `<th>` elements right for both horizontal and vertical using only markdown. But we should have a solution to abstract away the figure numbering and IDing. For example:

```html
<figure id="technical-profile">
<table>
  <tr>
    <th>Connection type</th>
    <td><a href="https://www.gsma.com/r/mobileeconomy/">2G or 3G</a></td>
  </tr>
  <tr>
    <th>Latency</th>
    <td>300 - 400ms</td>
  </tr>
  <tr>
    <th>Bandwidth</th>
    <td>0.4 - 1.6Mbps</td>
  </tr>
  <tr>
    <th>Phone</th>
    <td><a href="https://www.gsmarena.com/samsung_galaxy_s6-6849.php">Galaxy S6</a> — <a href="https://www.notebookcheck.net/A11-Bionic-vs-7420-Octa_9250_6662.247596.0.html">4x slower</a> than iPhone 8 (Octane V2 score)</td>
  </tr>
</table>
<figcaption>{{ figure_number() }} Technical profile of a typical mobile user.</figcaption>
</figure>
```

I've added `id="technical-profile"` to the `<figure>` and `{{ figure_number() }}` to the `<figcaption>`. The `figure_number` Jinja macro could generate a monotonically increasing figure number using shared state with the other figure macros. I'd love to hear any ideas to remove even more of the figure/figcaption boilerplate.

----

#### Summary

- Figure markup is a dark art that should be abstracted away so that authors can focus on the content.
- Numeric figure IDs are brittle and should be replaced with descriptive, human readable IDs.
- Figure numbers should be entirely automated.
- We should include more meta resources with figures to connect the results back to the source.

cc @HTTPArchive/developers

### PR DESCRIPTION
**Pull request by bazzadp**
Closes #1138 

@HTTPArchive/developers this is one I'd like to see if we can squeeze in before launch if we can.

This adds a drop down menu besides each figure which has SQL, Sheets or Image data:

Closed Menu

Which when opened gives a list of links:

Open Menu

This allows readers to more easily explore the data and opens up the HTTP Archive to newcomers, which is a key aim of the project.

Like our other menu, this defaults to a `<select>` element on mobile for ease of use, and it also works on tables and big-figures:

Mobile menu

There's a test release here so you can play with it: https://20201123t164931-dot-webalmanac.uk.r.appspot.com/en/2020/capabilities#fig-2

Now it's functional but obviously it looks absolutely awful, so we can't launch this. My CSS ain't great and after spending a small bit of time trying to hack this to get the menu to escape it's parent's confides and failing miserably, I've decided to ask for help, instead of trying to stumble a monstrosity across the finish line myself.

Are there any CSS wizards out there with a design eye that could finish off the design here? I'm happy to help with the HTML and templating for the functional side so it would be a collaboration between us.

I also need to internationalise the wording in the templates, but I can take care of that afterwards as know the templates really well. Just need help with the CSS.

Any takers? @catalinred you've a good eye and have done some great CSS work on the Almanac before so would love your help here. Or anyone else.

### CODE REVIEW

**Comment by rviscomi** [comment]
Thanks for kicking this off @bazzadp! This flew under my radar but I completely agree this would be great to have at launch. Here are some disorganized design suggestions for you or whoever wants to take this on:

- Move the button from the figcaption line to be absolutely positioned above the top right corner of the figure (chart/table/number). Moving it away from the figcaption helps to let the text flow to the full width of the space if needed and we don't need to worry about wrapping. Moving it to the top right corner is where I think people would look for menus. And above the figure, as opposed to overlapping, to ensure that it doesn't block the contents.
- Change to a three-dot or hamburger menu icon. A dropdown icon without text is very non-descript, but the dots/hamburger icons connote "more" or "options".
- Not sure how I feel about this being implemented as a `<select>` with native UI on mobile. I'd suggest styling a `<ul>` since it's such a short list of options and we don't gain much with the native UI. There also isn't really a concept of a "currently selected option" in this menu, so the checkbox seems out of place.

**Comment by bazzadp** [comment]
> Thanks for kicking this off @bazzadp! This flew under my radar but I completely agree this would be great to have at launch.

Yeah been in my to do list once I got templates in place I wanted them (now done!). And was wondering if the templates would put some people off so thought if I tackled that (the easy but IMHO!) then others can then build it and do the hard styling piece 😀

Luckily it’s very little change so far, as you can see from the PR so hopefully if we can make the styling changes over next few days, it’ll be low risk enough to launch because I think it would be great addition.

> Here are some disorganized design suggestions for you or whoever wants to take this on:
> 
> * Move the button from the figcaption line to be absolutely positioned above the top right corner of the figure (chart/table/number). Moving it away from the figcaption helps to let the text flow to the full width of the space if needed and we don't need to worry about wrapping. Moving it to the top right corner is where I think people would look for menus. And above the figure, as opposed to overlapping, to ensure that it doesn't block the contents.

Yeah I see that’s how it’s done in httparchive.org and only reason I didn’t do it there was because of tables. But absolutely, let’s look at this again once we get it looking prettier than what it does now.

> * Change to a three-dot or hamburger menu icon. A dropdown icon without text is very non-descript, but the dots/hamburger icons connote "more" or "options".

100% agree.

> * Not sure how I feel about this being implemented as a `<select>` with native UI on mobile. I'd suggest styling a `<ul>` since it's such a short list of options and we don't gain much with the native UI. There also isn't really a concept of a "currently selected option" in this menu, so the checkbox seems out of place.

Yeah I’m in two minds myself. I do think pop up menus on mobile aren’t great UX and `<select>` is what we’ve gone with on other menus including the year selector which is also small. But as you say that at least has a currently selected one. Definitely one to think about more.

How do you feel about having it on big figures ([example](https://20201123t164931-dot-webalmanac.uk.r.appspot.com/en/2020/markup#fig-1))? Overkill or useful? Guess it depends if we can make the design subtle enough that it doesn’t distract from that.

**Comment by rviscomi** [comment]
> How do you feel about having it on big figures (example)? Overkill or useful? Guess it depends if we can make the design subtle enough that it doesn’t distract from that.

It should be on all figures sourced from HA data, regardless of type, since readers should always have a way to drill down into the results and the queries that generated them. For that to work in practice, the buttons should be unobtrusive, especially because they're visible on every figure. To help readers know it's there but not get distracted by it, I think a combination of iconography (dots/burgers) and removing the default button border could help it blend in more seamlessly.

**Comment by rviscomi** [comment]
Is there anyone on @HTTPArchive/developers who can bring this over the finish line before the launch next week?

**Comment by rviscomi** [comment]
I'll work on this

**Comment by rviscomi** [comment]
Current version

image
image


Would love advice on:

- placement of the menu button to avoid awkward overlap with some wider figures like tables
- better default/hover/focus styles for the menu items
- how to close the menu upon re-click of the button
- how to integrate the description show/hide
- how to make it more accessible

**Comment by bazzadp** [comment]
Thanks so much @rviscomi for getting this to this much better state!

> Would love advice on:
> 
> * placement of the menu button to avoid awkward overlap with some wider figures like tables

I'm still not 100% convinced the top right is the correct location. Not sure it works for any of our three figure types to be honest:
- For graphs it appears far outside of the graph. Unlike the ones on HTTP Archive where it's basically part of the graph.
- For big figures and tables I don't think it's natural to expect it here.

Sure I can't persuade you to have it as part of the figure caption where it could be consistent for all?

Something like this:

image

> * better default/hover/focus styles for the menu items

Added this in https://github.com/HTTPArchive/almanac.httparchive.org/pull/1570/commits/823fb3a858366373be9a4504b70e901ec59bcd43. What do you think?

  

(Note blue line only appears of keyboard focus and not on mouse hover)

> * how to close the menu upon re-click of the button

Fixed in https://github.com/HTTPArchive/almanac.httparchive.org/pull/1570/commits/d3bcd5ec57aa42115d694b956b103e9e453fcc17. Was [due to use of SVG in the button](https://gomakethings.com/detecting-click-events-on-svgs-with-vanilla-js-event-delegation/)

> * how to integrate the figure description show/hide

Had a play with this and proving a bit tricky as it's a button whereas other elements are links. Don't you think this will be a bit odd?

Not loving the interaction of a button within a button, nor of hiding this so far away.

> * how to make the menu button hidden by default on desktop, visible only when hovering over the figure

I'm not sure we should do this. Won't that defeat much of the point of having this? You don't do this on the menus on https://httparchive.org/reports/state-of-the-web for example?

Also quite concerned with doing this AND hiding the description button in the menu. We put a lot of effort into these descriptions and so hiding them away, where you need either keyboard focus or hover concerns me.

> * how to make it more accessible

I think it's pretty accessible because we used our standard drop down. I did however add `aria-hidden` to the SVG as it's for display purposes and we have the label. Also internationalised it.

**Comment by rviscomi** [comment]
> Sure I can't persuade you to have it as part of the figure caption where it could be consistent for all?

I'd like to start with it in the top right corner and I'm be open to revisiting its positioning after launch.

> Had a play with this and proving a bit tricky as it's a button whereas other elements are links. Don't you think this will be a bit odd?

I think it's ok.

> Won't that defeat much of the point of having this?

I'm willing to drop the hidden until visible request.

Your style suggestions LGTM. I'll approve and you can merge if you think this is good to go.

**Review by rviscomi — APPROVED** [review]

**Comment by bazzadp** [comment]
I haven't addressed your table issue btw, as was waiting to see what you thought about moving to figcaption. Though couldn't repeat it myself to be honest so maybe not that common.

Still OK to merge or wanna have another look at that?

**Comment by rviscomi** [comment]
I'd prefer to merge what we have and also get a feel for it in action on the 2020 figures before iterating further.

**Comment by bazzadp** [comment]
SGTM!

**Pull request merged**
