### PR TITLE
Mobile web chapter: Figures added to markdown

### PR DESCRIPTION
**Pull request by obto**
Figures added to the markdown document

#910

### CODE REVIEW

**Comment by obto** [comment]
Have one last figure to add, just requested by Shubhie

**Comment by obto** [comment]
Done

**Review by spanicker — APPROVED** [review]
hmm I think you still hyphen when linking to sections and use the section names.
eg. data-sources vs. datasources
Otherwise LGTM.

**Comment by obto** [comment]
Good catch. Must have missed that change before I merged my work with the earlier PR

**Review by rviscomi — APPROVED** [review]

**Pull request merged**
