### PR TITLE
Oxford commas for Contributor teams

### PR DESCRIPTION
**Pull request by bazzadp**
Looks like we broke contributors with two teams for ebook in #1266 

Two teams screenshot

Still works for more that two teams:

Multiple teams screenshot

Let's move to Oxford commas for both Contributors and Ebook!

Staged here: https://20201218t132416-dot-webalmanac.uk.r.appspot.com/en/2020/contributors#ibnesayeed
And ebook here: https://20201218t132416-dot-webalmanac.uk.r.appspot.com/static/pdfs/web_almanac_2020_en.pdf

Screenshots:

Two teams screenshot fixed

Multiple teams screenshot fixed

### CODE REVIEW

**Review by rviscomi — APPROVED** [review]

**Review by ibnesayeed — COMMENTED** [review]
I would have liked it to be implemented as a [custom template filter](https://flask.palletsprojects.com/en/1.1.x/templating/#registering-filters), so that the conditional logic goes to pure Python files and can be reused everywhere we need oxford commas.

**Comment by bazzadp** [comment]
Think that's quite a bit bigger change but welcome to submit a PR for this.

**Comment by bazzadp** [comment]
Also in this case we want specific spans around the teams, so may not be as easy.

Will merge this and you can look at the custom filter option afterwards if you want @ibnesayeed

**Comment by ibnesayeed** [comment]
> Also in this case we want specific spans around the teams, so may not be as easy.

If Jinja supported supported list comprehensions, it would have been easy to create a list that has markup wrappers around each element before passing through oxford comma filter, but that's not the case.

**Pull request merged**
