### PR TITLE
Copyediting Caching chapter

### PR DESCRIPTION
**Pull request by bazzadp**
Part of https://github.com/HTTPArchive/almanac.httparchive.org/issues/218

Mostly standard editing, adding `alt` details, `<figure>` tags and the like.

@paulcalvano another enjoyable read. You didn't comment on my last review of your compression chapter so can you let us know if you plan to review this or are happy for us to merge away?

### CODE REVIEW

**Comment by rviscomi** [comment]
@bazzadp I've got 84 pending comments but GitHub is crashing when I try to submit them. The overall comments fit these categories:

- sentence case for headings
- full sentences for figcaptions
- code formatting for ALL HTTP header names (Cache-Control, Vary, etc)
- write out numbers less than 10

**Comment by bazzadp** [comment]
OK will have a look and hopefully bring that 84 list down!!

**Comment by bazzadp** [comment]
> @bazzadp I've got 84 pending comments but GitHub is crashing when I try to submit them. 😭
> 
> The overall comments fit these categories:
> 
> * sentence case for headings

Think I got these

> * full sentences for figcaptions

Not sure what you mean by this? I added full stops.

> * code formatting for ALL HTTP header names (Cache-Control, Vary, etc)

Done.

> * write out numbers less than 10 (unless used as a %)

Done.

I'm sure I missed some so could you see if you've any that aren't outdated and see if you can commit them?

**Comment by paulcalvano** [comment]
> @paulcalvano another enjoyable read. You didn't comment on my last review of your compression chapter so can you let us know if you plan to review this or are happy for us to merge away?

Apologies - I must have missed this.    The compression chapter looks good.   I'll have a look at your edits for the caching chapter right now.  Thanks for working on this!

**Comment by paulcalvano** [comment]
The edits look good to me. 

It looks like the image links are broken in the latest version when I view the markdown. Is this expected (ie, will they load correctly when pushed to the site, or do we need to fix something?).

**Comment by rviscomi** [comment]
> Not sure what you mean by this? I added full stops.

Some figcaptions are a mix of title case (Foo Bar Baz) and sentence case (Foo bar baz) and some have punctuation. All should be sentence case with punctuation.

**Comment by rviscomi** [comment]
I'm working on a branch of this branch with a few more minor copyedits as well as conversion of static images into Almanac-stylized interactive charts per #237.

**Comment by rviscomi** [comment]
Launching this chapter live shortly!

**Comment by bazzadp** [comment]
> The edits look good to me.
> 
> It looks like the image links are broken in the latest version when I view the markdown. Is this expected (ie, will they load correctly when pushed to the site, or do we need to fix something?).

This is expected. Looks beautiful in real life 😀: https://almanac.httparchive.org/en/2019/caching

**Comment by paulcalvano** [comment]
Awesome, thank you :)

**Pull request merged**
