### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by meyerweb**
Fixed a number of its/it's errors, plus a couple of minor edits to sentence structure.

### CODE REVIEW

**Comment by meyerweb** [comment]
I’m done with my edit pass.  Let me know if you want a similar pass for its/it's and than/then type errors in other chapters; I can do that once they’re finished with review and editing.

**Comment by bazzadp** [comment]
> Let me know if you want a similar pass for its/it's and than/then type errors in other chapters; I can do that once they’re finished with review and editing.

Hey @meyerweb, chapters with a tick in https://github.com/HTTPArchive/almanac.httparchive.org/issues/218 are, in theory, copyedited. If you want to give them another once over then I'm sure that would help! I know I, for one, am far from a professional copyeditor and am learning as we go through this so I'm sure the earlier chapters I "copyedited" (Third parties, PWA and Ecommerce) probably still have some mistakes in them!

**Comment by rviscomi** [comment]
Thanks @meyerweb! Can you make sure you add yourself to the [contributors file](https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/config/2019.json)? You've earned the `reviewers` and `editors` team badges :)

**Comment by meyerweb** [comment]
Done!

**Pull request merged**
