### PR TITLE
A few more edits to the fonts chapter

### PR DESCRIPTION
**Pull request by zachleat**
I think these are important as one of the edits made to the chapter says a thing that I do not necessarily agree with—thanks!

What additional work needs to be done here to get the Unedited flag removed?

### CODE REVIEW

**Comment by rviscomi** [comment]
> What additional work needs to be done here to get the Unedited flag removed?

The data visualizations also need to be generated, which I hope to get done this weekend.

**Comment by bazzadp** [comment]
> I think these are important as one of the edits made to the chapter says a thing that I do not necessarily agree with—thanks!

No problem with these changes, and apologies for putting words in your mouth! I felt the preconnect needed further clarification as per https://github.com/HTTPArchive/almanac.httparchive.org/pull/370#discussion_r344496636. Did tag you in that but think in the rush to publish we didn't have a huge amount of time to wait to hear back from you on this.

**Comment by zachleat** [comment]
@bazzadp oh naw it’s okay—I’ve been meaning to circle back to this too—wish I could’ve made it back sooner. Appreciate your help!

**Comment by bazzadp** [comment]
@zachleat could you update this line:

    last_updated: 2019-11-11T00:00:00.000Z

to:

    last_updated: 2019-11-15T00:00:00.000Z

Just so the sitemap picks it up? Outstanding issue for this (https://github.com/HTTPArchive/almanac.httparchive.org/issues/317) but for now it's manual!

**Comment by zachleat** [comment]
Done!

**Comment by bazzadp** [comment]
Thanks. Merged. Will let @rviscomi decide whether he wants to publish to prod now, or wait for visualisations.

**Pull request merged**
