### PR TITLE
Remove flags from language menu

### LINKED ISSUE #565: Get a source of country flags
What's the source of the country flag pngs? Or were they created from scratch?

For example: https://github.com/HTTPArchive/almanac.httparchive.org/blob/master/src/static/images/es.png

Need a French one and am sure that won't be the last!

### PR DESCRIPTION
**Pull request by bazzadp**
Closes #565 

Note I've also fixed the translation menu location in the footer as part of this and avoided some double divs!

### CODE REVIEW

**Comment by borisschapira** [comment]
I'm really not competent in art direction and/or US flag, so I'd rather not comment on this.

**Comment by AymenLoukil** [comment]
Hi!
Adding Countries flags is not coherent since we are not targeting specific regions. All the contents on Web Almanac are targeting language only and not language-country.

**Comment by bazzadp** [comment]
> Adding Countries flags is not coherent since we are not targeting specific regions. All the contents on Web Almanac are targeting language only and not language-country.

@AymenLoukil let’s take [that discussion to this issue](https://github.com/HTTPArchive/almanac.httparchive.org/issues/565#issuecomment-569424076) and not make this PR dependent on resolving that since a flag is part of the current design.

**Comment by rviscomi** [comment]
I'd suggest we close this PR per my comment in https://github.com/HTTPArchive/almanac.httparchive.org/issues/565#issuecomment-571279247

**Comment by bazzadp** [comment]
> I'd suggest we close this PR per my comment in [#565 (comment)](https://github.com/HTTPArchive/almanac.httparchive.org/issues/565#issuecomment-571279247)

Leave it open and I'll update it to remove flags instead. Almost done on that now...

**Comment by bazzadp** [comment]
Should be good to review and merge now. Updated title and initial comment too.

**Pull request merged**
