### PR TITLE
Copyedit 2021 Caching chapter

### LINKED ISSUE #2161: Caching 2021
# Part IV Chapter 23: Caching

Caching illustration

If you're interested in contributing to the Caching chapter of the 2021 Web Almanac, please reply to this issue and indicate which role or roles best fit your interest and availability: [author](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide), [reviewer](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide), [analyst](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide), and/or [editor](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide).

## Content team

| Lead | Authors | Reviewers | Analysts | Editors | Coordinator |
| --- | ------- | --------- | -------- | ------- | -- |
| @Zizzamia | @Zizzamia | @jessnicolet @WilhelmWillie @roryhewitt @boosef | @rviscomi | - | @rviscomi |

<details>
<summary><b>Expand for more information about each role</b></summary>

- The **[content team lead](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Content-Team-Leads'-Guide)** is the chapter owner and responsible for setting the scope of the chapter and managing contributors' day-to-day progress.
- **[Authors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide)** are subject matter experts and lead the content direction for each chapter. Chapters typically have one or two authors. Authors are responsible for planning the outline of the chapter, analyzing stats and trends, and writing the annual report.
- **[Reviewers](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Reviewers'-Guide)** are also subject matter experts and assist authors with technical reviews during the planning, analyzing, and writing phases.
- **[Analysts](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Analysts'-Guide)** are responsible for researching the stats and trends used throughout the Almanac. Analysts work closely with authors and reviewers during the planning phase to give direction on the types of stats that are possible from the dataset, and during the analyzing/writing phases to ensure that the stats are used correctly.
- **[Editors](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide)** are technical writers who have a penchant for both technical and non-technical content correctness. Editors have a mastery of the English language and work closely with authors to help wordsmith content and ensure that everything fits together as a cohesive unit.
- The **[section coordinator](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Section-Leads'-Guide)** is the overall owner for all chapters within a section like "User Experience" or "Page Content" and helps to keep each chapter on schedule.

_Note: The time commitment for each role varies by the chapter's scope and complexity as well as the number of contributors._

For an overview of how the roles work together at each phase of the project, see the [Chapter Lifecycle](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle) doc.
</details>

### [**0. Form the content team**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#0-create-content-team)
+ [x] **May 31**: The content team has at least one author, reviewer, and analyst

### [**1. Plan content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#1-plan-content)
+ [x] **June 15** The content team has completed the chapter outline in the [draft doc][~google-doc]

### [**2. Gather data**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#2-gather-data)
+ [x] **June 30**: Analysts have added all necessary [custom metrics](https://github.com/HTTPArchive/legacy.httparchive.org/blob/master/custom_metrics/README.md) and drafted a PR ([example](https://github.com/HTTPArchive/almanac.httparchive.org/pull/1087)) to track query progress
- **July 1 - 31**: HTTP Archive runs the July crawl

### [**3. Validate results**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#3-validate-results)
+ [x] **September 30**: Analysts have queried all metrics and saved the output to the [results sheet][~google-sheets]

### [**4. Draft content**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#4-draft-content)
+ [x] **October 31**: The content team has written, reviewed, and edited the chapter in the [doc][~google-doc]

### [**5. Publication**](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Chapter-Lifecycle#5-publication)
+ [x] **November 15**: The completed chapter and all required [metadata](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Authors'-Guide#metadata-to-add-at-the-top-of-your-chapters) and [figures](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Figures-Guide) are converted to markdown and submitted to [GitHub][~chapter-markdown]
- **December 1**: Target launch date 🚀

## Chapter resources

Refer to these 2021 Caching resources throughout the content creation process:

[📄 Google Docs][~google-doc] for outlining and drafting content
[🔍 SQL files][~sql-files] for committing the queries used during analysis
[📊 Google Sheets][~google-sheets] for saving the results of queries
[📝 Markdown file][~chapter-markdown] for publishing content and managing public metadata

[~google-doc]: https://docs.google.com/document/d/1BSdljOv86CPAP5T0A9jcV6bU7NJp1f2mTFa4ZZ7xxe8/edit?usp=sharing
[~sql-files]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/sql/2021/caching
[~google-sheets]: https://docs.google.com/spreadsheets/d/1-v3yR0LZIC3t4zWtqTgR3jJsKjjRMP-HATU2caP8e2c/edit?usp=sharing
[~chapter-markdown]: https://github.com/HTTPArchive/almanac.httparchive.org/tree/main/src/content/en/2021/caching.md

### LINKED ISSUE #2525: Edit 2021 chapters
📢  Attention Editors: this issue will be used to track progress on the 2021 chapters that are ready for editing.

When you're ready to edit a chapter, edit this comment to put your name next to the first unchecked and unclaimed chapter. Chapters will be added to the queue as they become ready for editing.

Refer to the [Editors' Guide](https://github.com/HTTPArchive/almanac.httparchive.org/wiki/Editors'-Guide) for general best practices.

Staged URL (with all above chapters turned on): https://20211116t174953-dot-webalmanac.uk.r.appspot.com/en/2021/

- [x] Structured Data - @tunetheweb 
- [x] Third Parties - @rviscomi 
- [x] Performance - @rviscomi / @tunetheweb 
- [x] Privacy - @tunetheweb 
- [x] Capabilities - @tunetheweb 
- [x] PWA - @rviscomi 
- [x] Resource Hints - @rviscomi 
- [x] CSS - @shantsis 
- [x] CMS - @shantsis 
- [x] Mobile Web - @shantsis 
- [x] Ecommerce - @shantsis 
- [x] Accessibility - @tunetheweb 
- [x] CDN - @shantsis 
- [x] Security - @tunetheweb 
- [x] WebAssembly - @shantsis 
- [x] JavaScript - @shantsis @rviscomi 
- [x] Page Weight - @tunetheweb 
- [x] Compression - @shantsis 
- [x] Jamstack - @shantsis 
- [x] SEO - @tunetheweb 
- [x] HTTP - @shantsis 
- [x] Markup - @rviscomi 
- [x] Media - @tunetheweb 
- [x] Caching - @tunetheweb

### PR DESCRIPTION
**Pull request by tunetheweb**
Closes #2161 
Closes #2525 

Staging link: https://20211214t234930-dot-webalmanac.uk.r.appspot.com/en/2021/caching

Standard enough copy edit. Many changes were:
- Moved figures above discussion of them, as per Web Almanac style
- Changed [figure 15](https://20211214t234930-dot-webalmanac.uk.r.appspot.com/en/2021/caching#fig-15) to a stacked bar chart as thought it looked better as these add up to 100%
- Added [figure 17](https://20211214t234930-dot-webalmanac.uk.r.appspot.com/en/2021/caching#fig-17) as was a lot of discussion of first-party versus third-party but only had a first-party figure previously.

This is the last chapter to merge and keen to get this wrapped up so let me know ASAP if any major issues with this edit. If not, let's merge and launch!

### CODE REVIEW

**Comment by tunetheweb** [comment]
Any thoughts on this @Zizzamia / @jessnicolet ? Am I good to merge and release your hard work?

**Comment by Zizzamia** [comment]
Reading :)

**Review by Zizzamia — APPROVED** [review]
🌲🚀🌕

**Comment by tunetheweb** [comment]
Woo hoo!!!

**Pull request merged**
