### PR TITLE
Performance 2020 queries adjustments

### PR DESCRIPTION
**Pull request by max-ostapenko**
Progress on #905

### CODE REVIEW

**Comment by max-ostapenko** [comment]
@dooman87 I created this PR to merge some minor adjustments caused by tweaking input data for charts.
Feel free to commit if needed.

**Comment by rviscomi** [comment]
Please mark as "Ready for review" when ready.

**Comment by dooman87** [comment]
Thanks @max-ostapenko, I think I'm alright atm. Looks good to me - feel free to merge.

**Comment by rviscomi** [comment]
@max-ostapenko is this ready for review?

**Comment by max-ostapenko** [comment]
@rviscomi I'd like to keep it open till we get all feedback from authors and finalise visualisations for the chapter.
And currently, I've got some ideas this weekend to improve the readability of queries.

**Comment by rviscomi** [comment]
Ok, sounds good. I assume @thefoxis is on board with that plan and reviewing the results?

**Comment by rviscomi** [comment]
@max-ostapenko @thefoxis have the results been reviewed? If these are the only remaining queries left to be updated, let's get them reviewed and merged ASAP.

**Comment by max-ostapenko** [comment]
@rviscomi I think we can review and merge this to keep the PRs in-progress to the minimum.

**Review by rviscomi — APPROVED** [review]

**Pull request merged**
