### PR TITLE
Removes copyright year from footer

### LINKED ISSUE #948: Remove the year from the footer copyright
@bazzadp what do you think is the best way to do this? The 2020 template extends 2019, which sets ©️ 2019 in each lang's localized base template.

I think it's ok if the copyright year was defined in one central place and all pages/langs/editions inherit the latest year. Bonus points if we don't need to manually increment it each year.

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes #948

### CODE REVIEW

**Comment by bazzadp** [comment]
Good stuff! Can you submit a PR to add yourself to `src/config/2020.json` in `development` team? They are in alphabetical order by first name btw.

You can do this either as part of this PR or as a separate one.

**Comment by rviscomi** [comment]
_Aside: @bazzadp can we have a linter that checks that the contributor was added in the right sort order? 😅_

**Comment by bazzadp** [comment]
> _Aside: @bazzadp can we have a linter that checks that the contributor was added in the right sort order? 😅_

My OCD suffices for that for now 😁

**Comment by SaptakS** [comment]
> Good stuff! Can you submit a PR to add yourself to `src/config/2020.json` in `development` team? They are in alphabetical order by first name btw.
> 
> You can do this either as part of this PR or as a separate one.

I will add it as part of this PR itself.

**Pull request merged**
