### PR TITLE
Stop having comma for two person lists

### LINKED ISSUE #1247: Comma separating two contributors
On chapter pages like [Media](https://almanac.httparchive.org/en/2019/media), when there are two authors or reviewers, the contributor names are separated by ", and".

I would only expect the names to be separated by "and". For example:

A
A and B
A, B, and C

image

This affects both the chapter pages and the ebook.

### PR DESCRIPTION
**Pull request by bazzadp**
Fixes #1247

### CODE REVIEW

**Review by DoubleRR7244 — APPROVED** [review]
I will change my way for my HEAVENLY FATHER AND JESUS CHRIST MY LORD AND SAVIOR AMEN!!!...

**Review by DoubleRR7244 — APPROVED** [review]

**Comment by rviscomi** [comment]
Welcome @DoubleRR7244. Thanks for reviewing this PR, but we haven't seen you around this project before and I see from your profile that you're new to GitHub. Please let us know if you're interested in contributing to the Web Almanac.

Also, please be aware that making comments like that is irrelevant to the discussion and inappropriate. It appears to be spam, but I'll give you the benefit of the doubt being that you're new to the social customs of the GitHub community. If there are more comments like that, I'll have to assume it's spam and take appropriate action.

**Review by rviscomi — APPROVED** [review]
LGTM 😅

**Review by DoubleRR7244 — COMMENTED** [review]
[](https://www.instagram.com/p/CEtaZHij0jO/?igshid=1ftof8r5rvsva)

**Pull request merged**
