### PR TITLE
Jamstack 2020 queries: Add Nuxt.js and Docusaurus

### PR DESCRIPTION
**Pull request by denar90**
Progress on https://github.com/HTTPArchive/almanac.httparchive.org/issues/1736

Also I've updated spread sheet with latest results. cc @ahmadawais

### CODE REVIEW

**Comment by rviscomi** [comment]
Thanks @denar90! I've changed your comment from "Fixes" to "Progress on" so that we can keep the issue open until the markdown changes are made, including any text and figure changes.

**Review by rviscomi — APPROVED** [review]

**Comment by ahmadawais** [comment]
@denar90 thabks for all your work. Can you update this to include Sphinx, GitBook, MkDoc, and YUI doc? Take a look at the relevant discussion in the issue you tagged above, doc tools that I listed above are producing SSGs and have over 100 sites so we should use the opportunity to include these alongside Docusaurus. 🙌

**Comment by denar90** [comment]
Thank you 🙏 
Of course we can add Sphinx, GitBook, MkDocs, and YUI. Just nit question, are we sure they are Jamstack related? cc @remotesynth

**Comment by remotesynth** [comment]
I kind of have the same concern as @denar90. We seem to be getting off the main point of this research. I'd rather see Docusaurus removed and not cover documentation generators than to see all these added. I wouldn't call these Jamstack tools since they are a) very specific to documentation and b) purely static site generators. For example, YUIdoc is just an API docs generator - this is not for building Jamstack applications.

**Comment by bazzadp** [comment]
To be honest, based on my analysis in https://github.com/HTTPArchive/almanac.httparchive.org/issues/1736#issuecomment-74313597 I’m not sure edits work arguing over. Not of the documentation tools will even register compared to other Jamstack usage. So either leave them all out or include them but all but don’t think it’ll make much difference either way to be honest.

**Comment by denar90** [comment]
I tend to agree with @remotesynth 
Are we ok removing doc tools ? Also cc @rviscomi @ahmadawais

**Pull request merged**
