### PR TITLE
Media 2024 queries

### PR DESCRIPTION
**Pull request by stefanjudis**
This PR includes the updated queries for the media chapter. #3596

### CODE REVIEW

**Comment by mgifford** [comment]
How do you get around the of blocked regex 'TABLESAMPLE' error? I don't actually know what it does mind you...

**Comment by stefanjudis** [comment]
@mgifford I'm sorry, I don't understand. What error?

**Comment by tunetheweb** [comment]
`TABLESAMPLE SYSTEM (0.001 PERCENT)` says only run this on 0.001% of the rows in the table. This is good during query development as faster (and cheaper!) to run than on the full dataset.

However, eventually we will want all queries run on the full dataset. Therefore there is a linting rule warning this is being used and we should not merge this PR until that is fixed.

So it's fine to ignore it for now (especially as this PR is still in Draft status) if you're still working on those queries. It just means you won't see a nice green tick in the linting check for now and also that you might miss other linting errors unless you explicitly look at those checks to see if anything else needs fixing too.

**Comment by stefanjudis** [comment]
Aaaah, I didn't realize there was a linting error. Thanks @tunetheweb!

I've run most of the queries against the full data set already. and will double check that this is true!

**Review by tunetheweb — APPROVED** [review]
Looks pretty good to me. Still using some older tables in some queries but let's not perfection be the enemy of the good!

Let me know if good to merge, but I think you might still be working on some queries?

**Pull request merged**
