### PR TITLE
Add zcorpan's twitter handle in 2019.json

### PR DESCRIPTION
**Pull request by zcorpan**

### CODE REVIEW

**Comment by zcorpan** [comment]
https://almanac.httparchive.org/en/2019/contributors says "Brainstormers" for me, but the JSON includes both "brainstormers" and "reviewers". How come?

**Comment by rviscomi** [comment]
@zcorpan the live website was deployed from a stale snapshot so it won't be reflecting the latest config changes.

**Comment by bazzadp** [comment]
@zcorpan see the slack channel:

bkardell 12:29
I'm not in a place where I have handy access just now but a quick look at the preview shows zcorpan is under credited. He is the primary reviewer on the markup chapter

So.. I'll try to remember to send a pull but.. Just in case I don't..
Barry Pollard 12:41
Added him to reviewers team @bkardell as part of https://github.com/HTTPArchive/almanac.httparchive.org/pull/272. @rick will you update the spreadsheet too?

**Comment by rviscomi** [comment]
Sheet updated

**Comment by zcorpan** [comment]
Thanks!

**Pull request merged**
