### PR TITLE
Switch to hi-res images for Twitter as slightly blurred now

### LINKED ISSUE #534: Use larger images for social metadata
For example, the appearance of this chapter image is a bit low-res:

image

We should use `hero_lg.jpg` for these images as opposed to `hero_sm.jpg`

https://github.com/HTTPArchive/almanac.httparchive.org/blob/d52cb47873d3bcbd558a523d4697d71f269ed92b/src/templates/en/2019/chapter.html#L27-L32

### PR DESCRIPTION
**Pull request by bazzadp**
Closes #534

### CODE REVIEW

**Comment by rviscomi** [comment]
@bazzadp did you also say once that it's possible to prompt Twitter to reload hero images used in existing tweets?

**Comment by bazzadp** [comment]
Yes. Once this is released I’ll run the 20 chapter URLs through the [Twitter Card Validator](https://cards-dev.twitter.com/validator) and apparently that forces a refresh of Twitter’s image cache.

**Comment by borisschapira** [comment]
@bazzadp From experience, you need to run them with a querystring to force cache invalidation.

**Comment by bazzadp** [comment]
Will give that a go if it doesn’t work but that was sufficient last time.

Btw can you accept https://github.com/HTTPArchive/almanac.httparchive.org/pull/564#discussion_r352096562 now this is merged?

**Comment by bazzadp** [comment]
FYI released and all refreshed now.

No URL params needed but you do need to do another Twitter search to pick up the new images (just F5-ing your browser won't do it).

Also it blocked me after about 10 of them, but did the rest in another browser and fine. Must be some sort of rate limiting.

Anyway all good now!

**Pull request merged**
