### PR TITLE
Update Missing character

### PR DESCRIPTION
**Pull request by SilentJMA**
a missing "F"

### CODE REVIEW

**Comment by bazzadp** [comment]
Good spot!

Can you run `npm run generate` from the src directory? That will generate the corresponding HTML file from this markdown.

**Comment by bazzadp** [comment]
Why'd you close it @SilentJMA ? This was a good change to commit.

**Comment by SilentJMA** [comment]
> Good spot!
> 
> Can you run `npm run generate` from the src directory? That will generate the corresponding HTML file from this markdown.

you know im at work(manager logistics) / working and translating from online editor hhhh

**Comment by bazzadp** [comment]
> you know im at work(manager logistics) / working and translating from online editor hhhh

Thats fine. I'll merge this then and run `npm run generate` in a later PR.

**Pull request merged**
