### PR TITLE
Fix some 404s

### PR DESCRIPTION
**Pull request by bazzadp**

### CODE REVIEW

**Comment by rviscomi** [comment]
Great catches! Surprised GitHub doesn't redirect when users rename themselves.

**Comment by bazzadp** [comment]
Yeah that's annoying. Hope you don't me just merging these minor typos and 404s. Will give you a chance to review actual code changes (see #717 btw!)

**Comment by bazzadp** [comment]
Ah it's because of this: https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/changing-your-github-username

> After changing your username, your old username becomes available for anyone else to claim. Most references to your repositories under the old username automatically change to the new username. However, some links to your profile won't automatically redirect.

They could redirect in meantime until someone claims it but guess that doesn't really free it up for it to be claimed!

**Comment by rviscomi** [comment]
Feel free to merge trivial PRs without explicit approval.

**Pull request merged**
